name: Rust - Test
on: [ pull_request ]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update
      - name: Build Rust project
        run: cargo build --release
      - name: Test Rust project
        run: cargo test --release
